blogging/urls.py
from . import views
from django.urls import path

app_name,urlpatterns ="blogging", [
    path("", views.index_view, name="index-view"),
    path("<int:id>/", views.detail_view, name="detail-view"),
]

landing/urls.py
from . import views
from django.urls import path

app_name, urlpatterns = "landing", [
    path("", views.index_view, name="index-view"),
    path("mda/", views.mda_view, name="mda-view"),
    path("about-us/", views.about_view, name="about-view"),
    path("service/", views.service_view, name="service-view"),
    path("project/", views.project_view, name="project-view"),
    path("contact-us/", views.contact_view, name="contact-view"),
    path("government/<id>/", views.government_view, name="government-view"),
]

website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [ 
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path("blog/", include("blogging.urls")),
    path('markdownx/', include('markdownx.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogging/models.py
from django.db import models
from markdownx.utils import markdownify
from markdownx.models import MarkdownxField


class Blog(models.Model):
    content = MarkdownxField(default="")
    summary = models.TextField(blank=True)
    title = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="blog_images", blank=True, null=True)

    @property
    def formatted_content(self):
        return markdownify(self.content)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title.title()

landing/models.py
from django.db import models
from markdownx.utils import markdownify
from markdownx.models import MarkdownxField


class Sector(models.Model):
    name = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name.title()


class Govenance(models.Model):
    content = MarkdownxField(default="")
    name = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    sector = models.ForeignKey(Sector, models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def formatted_content(self):
        return markdownify(self.content)

    def __str__(self) -> str:
        return f"{self.name} - {self.sector.name}"


class ProjectStatus(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Project(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=200)
    description = MarkdownxField(default="")
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(ProjectStatus, on_delete=models.PROTECT)

    @property
    def formatted_description(self):
        return markdownify(self.description)

    def __str__(self):
        return f"{self.name} - {self.status.name}"


class Contact(models.Model):
    email = models.EmailField()
    message = models.TextField()
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    subject = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.subject}"

landing/forms.py
from . import models
from django import forms


class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ["name", "email", "phone", "subject", "message"]

blogging/views.py
from . import models
from django.shortcuts import render
from website.decorator import set_sectors_with_governance


@set_sectors_with_governance
def index_view(request):
    blogs = models.Blog.objects.all()

    context = {"blogs": blogs}
    return render(request, "blogging/index.html", context)


@set_sectors_with_governance
def detail_view(request, id):
    blog = models.Blog.objects.get(id=id)

    context = {"blog": blog}
    return render(request, "blogging/detail.html", context)

landing/views.py
from . import forms, models
from blogging.models import Blog
from django.contrib import messages
from django.shortcuts import render, redirect
from website.decorator import set_sectors_with_governance


@set_sectors_with_governance
def index_view(request):
    blogs = Blog.objects.all()[:4]

    context = {"blogs": blogs}
    return render(request, "landing/index.html", context)


@set_sectors_with_governance
def about_view(request):
    return render(request, "landing/about.html")


@set_sectors_with_governance
def mda_view(request):
    return render(request, "landing/mda.html")


@set_sectors_with_governance
def service_view(request):
    return render(request, "landing/service.html")


@set_sectors_with_governance
def project_view(request):
    projects = models.Project.objects.all()
    statuses = models.ProjectStatus.objects.all()

    filter_attr = request.GET.get("filter")

    if filter_attr:
        projects = projects.filter(status__id=int(filter_attr))

    context = {
        "projects": projects,
        "statuses": statuses,
    }
    return render(request, "landing/project.html", context)


@set_sectors_with_governance
def government_view(request, id):
    member = models.Govenance.objects.get(id=id)

    context = {"member": member}
    return render(request, "landing/government.html", context)


@set_sectors_with_governance
def contact_view(request):
    if request.method == "POST":
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            messages.error(request, "Something went wrong")

        return redirect("landing:contact-view")
    return render(request, "landing/contact.html")

blogging/templates/blogging.html
{% load static heroicons tailwind_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  {% tailwind_css %}
  <meta charset="UTF-8" />
  <title>Governemnt Site</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous" />
  {% block head %}{% endblock head %}
  <style>
    header {
      nav {
        overflow: hidden;

        &.show {
          overflow: visible;
        }

        @media screen and (min-width: 768px) {
          overflow: visible;
        }
      }
    }
  </style>
</head>

<body class="w-full flex flex-col overflow-auto">
  <header
    class="w-full items-center justify-between bg-whte sticky top-0 py-4 flex gap-4 px-[10%] z-50 bg-white shadow-md">
    <a href="{% url 'landing:index-view' %}"><img src="{% static 'logo.png' %}" alt="" class="h-12" /></a>

    <nav id="header-navbar" style="font-variant: small-caps;"
      class="grow flex gap-4 md:gap-20 whitespace-nowrap py-4 md:py-0 rounded-sm md:rounded-none items-center justify-end flex-col md:flex-row right-4 md:right-auto top-32 transition-all shadow-md md:shadow-none bg-white md:top-auto absolute md:relative w-0 md:w-auto">
      <a href="{% url 'landing:about-view' %}"
        class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline">about</a>
      <a href="{% url 'landing:contact-view' %}"
        class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline">contact us</a>
      <div
        class="text-slate-700 md:underline no-underline underline-offset-2 hover:no-underline relative peer [&:hover>div]:flex">
        <span class="">government</span>
        <div class="absolute top-full right-0 md:right-4 w-60 bg-white shadow-2xl z-10 hidden transition-all flex-col text-sm">
          {% for sector in request.sectors %}
          <button style="font-variant: small-caps;"
            class="relative w-full no-underline px-4 py-2 text-slate-600 hover:bg-slate-600 hover:text-white transition-all text-left group">
            <span>{{ sector.name|lower }}</span>
            <div
              class="absolute bottom-full md:bottom-[initial] md:top-0 -right-14 md:right-56 w-60 bg-white shadow-xl z-20 group-hover:flex hidden transition-all flex-col text-sm">
              {% for govenance in sector.govenance_set.all %}
              <a href="{% url 'landing:government-view' govenance.id %}" style="font-variant: small-caps;"
                class="relative w-full no-underline px-4 py-2 text-slate-600 hover:bg-slate-600 hover:text-white transition-all text-left group">
                {{ govenance.name|lower }}
              </a>
              {% endfor %}
            </div>
          </button>
          {% endfor %}
        </div>
      </div>
      <a href="{% url 'landing:mda-view' %}"
        class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline uppercase">mda</a>
        <a href="{% url 'landing:project-view' %}"
        class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline">project</a>
        <a href="{% url 'blogging:index-view' %}"
          class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline">news <span class="lowercase">and</span> update</a>
    </nav>

    <div class="h-6 w-6 flex md:hidden cursor-pointer" onclick="toggleNavbar()">
      {% heroicon_outline 'bars-2' %}
    </div>
  </header>
  <main class="grow flex flex-col">
    {% block content %}

    {% endblock %}
  </main>

  <footer class="bg-white dark:bg-gray-900">
    <div class="container px-6 py-8 mx-auto">
      <div class="flex flex-col items-center text-center">
        <a href="{% url 'landing:index-view' %}"><img class="w-auto h-7" src="{% static 'logo.png' %}" alt="" /></a>

        <p class="max-w-md mx-auto mt-4 text-gray-500 dark:text-gray-400">Kano State Government</p>

        <div class="flex flex-col gap-2 mt-4 sm:flex-row sm:items-center sm:justify-center">
          <a href="{% url 'landing:about-view' %}"
            class="w-full px-5 py-2 no-underline text-sm tracking-wide text-green-600 capitalize transition-colors duration-300 transform bg-white rounded-md sm:mx-2 sm:order-2 sm:w-auto hover:bg-white border-2 border-green-600 focus:outline-none focus:ring focus:ring-green-300 focus:ring-opacity-80">Know
            more</a>
          <a href="{% url 'landing:mda-view' %}"
            class="w-full px-5 py-2 no-underline text-sm tracking-wide text-white capitalize transition-colors duration-300 transform bg-green-600 rounded-md sm:mx-2 sm:order-2 sm:w-auto hover:bg-green-500 focus:outline-none focus:ring focus:ring-green-300 focus:ring-opacity-80">Get
            started</a>
        </div>
      </div>

      <hr class="my-10 border-gray-200 dark:border-gray-700" />

      <div class="flex flex-col items-center sm:flex-row sm:justify-between">
        <p class="text-sm text-gray-500">© Copyright 2024. All Rights Reserved.</p>

        <div class="flex mt-3 -mx-2 sm:mt-0">
          <a href="{% url 'blogging:index-view' %}"
            class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300"
            aria-label="Reddit">News</a>

          <a href="{% url 'landing:about-view' %}"
            class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300"
            aria-label="Reddit">About</a>

          <a href="{% url 'landing:contact-view' %}"
            class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300"
            aria-label="Reddit">Contact Us</a>
        </div>
      </div>
    </div>
  </footer>
</body>
<script>
  function toggleNavbar() {
    console.log("hello world")
    let navbar = document.querySelector('#header-navbar');
    navbar.classList.toggle('w-52');
    navbar.classList.toggle('show');
  }
</script>

</html>

blogging/templates/blogging/detail.html
{% extends 'landing.html' %}

{% block content %}
  <section class="mb-4 px-28 md:mb-0 w-full mx-auto relative">
    <div class="flex flex-col items-center px-20 py-10 text-center">
      <h2 class="text-4xl font-semibold text-gray-800 leading-tight">{{ blog.title }}</h2>
      {% comment %} <a href="#" class="py-2 text-green-700 inline-flex items-center justify-center mb-2">Cryptocurrency</a> {% endcomment %}
    </div>

    <img src="{{ blog.image.url }}" class="mx-auto object-cover lg:rounded" style="height: 30em;" />
  </section>

  <section class="flex flex-col w-full px-28 items-center">{{ blog.formatted_content|safe }}</section>
{% endblock %}

blogging/templates/blogging/index.html
{% extends 'landing.html' %}

{% block content %}
  <section class="relative flex px-28 flex-col justify-start pt-10 overflow-hidden">
    <div class="mx-auto w-full">
      <h2 class="font-bold text-center text-6xl text-slate-700 font-display">Blogging</h2>
      <p class="text-center mt-4 font-medium text-slate-500">- Miorena tsara -</p>

      <div class="rounded-lg overflow-hidden mt-10 relative before:absolute before:z-20 before:bg-black before:h-full before:w-full before:bg-gradient-to-tr before:from-black before:to-emerald-600 before:opacity-80">
        <img src="https://loremflickr.com/320/240?random=1" class="absolute z-10 object-cover h-80 w-full h-full" alt="" />
        <a href="" class="absolute z-20 top-1/2 right-20 text-white -translate-y-1/2">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-20 h-20">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.91 11.672a.375.375 0 0 1 0 .656l-5.603 3.113a.375.375 0 0 1-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112Z" />
          </svg>
        </a>

        <div class="relative z-20 p-10 h-full w-1/2">
          <h2 class="text-white text-3xl font-semibold">ASA fitoriana ny filazantsara iarivo avaradrano</h2>
          <h3 class="text-white text-xl">Docteur Irako Andriamahasoa Ammi</h3>
          <p class="text-sm text-slate-200 mt-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga veritatis officiis cupiditate sed sint natus alias placeat, asperiores tempore reiciendis.</p>
          <div class="flex gap-4 items-center pt-4 border-t border-slate-300 text-slate-300 mt-6">
            <span class="flex gap-1 items-center text-sm">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
              </svg>35
            </span>
            <span class="flex gap-1 items-center text-sm">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="text-sky-400 w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
              </svg>20
            </span>
            <span class="flex gap-1 items-center text-sm">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 text-lime-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
              </svg>15
            </span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="text-gray-600 body-font py-10">
    <div class="container px-5 mx-auto">
      <div class="flex flex-wrap -m-4">
        {% for blog in blogs %}
          <div class="p-4 md:w-1/3">
            <div class="h-full rounded-xl shadow overflow-hidden">
              <img class="lg:h-48 md:h-36 w-full object-cover object-center scale-110 transition-all duration-400 hover:scale-100" src="{{ blog.image.url }}" alt="blog" />
              <div class="p-6">
                {% comment %} <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">CATEGORY-1</h2> {% endcomment %}
                <h1 class="title-font text-lg font-medium text-gray-600 mb-3">{{ blog.title }}</h1>
                <p class="leading-relaxed mb-3 line-clamp-3">{{ blog.summary }}</p>
                <div class="flex items-center flex-wrap">
                  <a href="{% url 'blogging:detail-view' blog.id %}" class="hover:scale-105 drop-shadow-md shadow px-4 py-1 rounded-lg">Learn more</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

landing/templates/components/banner.html
{% load static %}

<section class="w-full flex flex-col items-center justify-center relative gap-2 text-white py-40 md:py-60 min-h-80">
  <img src="{% static 'banner.webp' %}" alt="" class="absolute w-full h-full object-cover brightness-50" />

  <div class="z-10 flex flex-col gap-4 text-center items-center justify-center px-[10%] md:px-[20%]">
    <h2 class="text-2xl md:text-4xl font-bold">Promoting Good Governance and Development</h2>
    <span class="text-sm md:text-base">Kano State Government is committed to ensuring sustainable development, enhancing the quality of life for all residents, and fostering economic growth through various initiatives and programs.</span>

    <div style="font-variant: small-caps;" class="mt-8 md:mt-4 flex gap-4 text-xs md:text-base">
      <a href="{% url 'landing:about-view' %}" class="px-6 py-1 border border-white transition-all hover:bg-white hover:text-black">learn more</a>
      <a href="{% url 'landing:project-view' %}" class="px-6 py-1 border border-white transition-all hover:bg-white hover:text-black">our projects</a>
    </div>
  </div>
</section>

landing/templates/components/footer.html
{% load static %}

<footer class="bg-white dark:bg-gray-900">
  <div class="container px-6 py-8 mx-auto">
    <div class="flex items-center justify-between text-center">
      <a class="" href="{% url 'landing:index-view' %}"><img class="w-auto h-10" src="{% static 'logo.png' %}" alt="" /></a>
      <p class="max-w-md text-gray-200 font-bold text-lg dark:text-gray-400">Kano State Government</p>

      <div style="font-variant: small-caps;" class="mt-8 md:mt-4 flex gap-4 text-xs md:text-base text-white">
        <a href="{% url 'landing:about-view' %}" class="px-6 py-1 border border-white transition-all hover:bg-white hover:text-black">learn more</a>
        <a href="{% url 'landing:mda-view' %}" class="px-6 py-1 border border-white transition-all hover:bg-white hover:text-black">get started</a>
      </div>
    </div>

    <hr class="my-10 border-gray-200 dark:border-gray-700" />

    <div class="flex flex-col items-center sm:flex-row sm:justify-between">
      <p class="text-sm text-gray-500">© Copyright 2024. All Rights Reserved.</p>

      <div class="flex mt-3 -mx-2 sm:mt-0">
        <a href="{% url 'blogging:index-view' %}" class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300" aria-label="Reddit">News</a>
        <a href="{% url 'landing:about-view' %}" class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300" aria-label="Reddit">About</a>
        <a href="{% url 'landing:contact-view' %}" class="mx-2 text-sm text-gray-500 transition-colors duration-300 hover:text-gray-500 dark:hover:text-gray-300" aria-label="Reddit">Contact Us</a>
      </div>
    </div>
  </div>
</footer>

landing/templates/components/header.html
{% load static heroicons %}

<style>
  header {
    nav {
      @media screen and (max-width: 768px) {
        box-shadow: -20em 0 0 20em rgba(0 0 0 / 0.9);
      }
    }
  }
</style>

<header class="w-full gap-4 flex items-center justify-between bg-white z-50 top-0 sticky shadow py-4 px-[10%]">
  <a href="{% url 'landing:index-view' %}" class="flex items-center gap-2 flex-1 z-10">
    <img src="{% static 'logo.png' %}" alt="" class="h-14 md:h-20" />
    <span class="capitalize font-semibold text-center leading-4 md:text-base text-sm">kano state government</span>
  </a>

  <nav class="z-50 bg-white md:bg-transparent flex-auto flex-col md:flex-row flex items-end md:items-center pl-4 p-[25%_15%] duration-500 md:p-0 md:justify-end whitespace-nowrap gap-10 fixed md:relative top-0 right-0 h-screen md:h-full w-4/5 md:w-full transition-all opacity-0 md:opacity-100 translate-x-full md:translate-x-0" style="font-variant: small-caps;">
    <button class="w-8 h-8 flex md:hidden absolute top-4 right-8" onclick="document.querySelector('header nav').classList.add('translate-x-full', 'opacity-0')">
      <input type="checkbox" class="w-full h-full cursor-pointer absolute top-0 left-0 opacity-0" />
      {% heroicon_outline 'x-mark' %}
    </button>

    <a href="{% url 'landing:about-view' %}" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base">about</a>
    <a href="{% url 'landing:contact-view' %}" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base">contact us</a>
    <button style="font-variant: small-caps;" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base relative cursor-text group">
      <span class="cursor-pointer">government</span>
      <div class="w-60 absolute top-full right-0 md:right-4 bg-white flex flex-col rounded shadow opacity-0 pointer-events-none hover:pointer-events-auto group-hover:pointer-events-auto hover:opacity-100 group-hover:opacity-100 delay-500 group-hover:delay-0">
        {% for sector in request.sectors %}
          <buton class="w-full text-left relative">
            <span class="w-full px-4 py-2 inline-block peer transition-all hover:bg-slate-500 hover:text-white cursor-pointer">{{ sector.name|lower }}</span>
            <div class="absolute flex flex-col w-full left-10 z-10 md:left-28 top-full bg-white shadow opacity-0 pointer-events-none hover:pointer-events-auto peer-hover:pointer-events-auto hover:opacity-100 peer-hover:opacity-100">
              {% for govenance in sector.govenance_set.all %}
                <a href="{% url 'landing:government-view' govenance.id %}" class="w-full p-2 px-4 text-slate-700 hover:text-white hover:bg-slate-400 transition-all no-underline text-lg md:text-base">{{ govenance.name|lower }}</a>
              {% endfor %}
            </div>
          </buton>
        {% endfor %}
      </div>
    </button>
    <a href="{% url 'landing:project-view' %}" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base">project</a>
    <a href="{% url 'blogging:index-view' %}" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base">news</a>
    <a href="{% url 'landing:mda-view' %}" class="text-slate-700 no-underline md:underline underline-offset-2 hover:no-underline text-lg md:text-base">mda</a>
  </nav>

  <button class="w-8 h-8 flex md:hidden relative" onclick="document.querySelector('header nav').classList.remove('translate-x-full', 'opacity-0')">
    <input type="checkbox" class="w-full h-full cursor-pointer absolute top-0 left-0 opacity-0" />
    {% heroicon_outline 'bars-3' %}
  </button>
</header>

landing/templates/landing.html
{% load static heroicons tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="UTF-8" />
    <title>Kano State Government</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}

    {% endblock %}
  </head>
  <body class="h-full w-screen flex flex-col overflow-y-auto overflow-x-hidden">
    {% include 'components/header.html' %}

    <main class="grow flex flex-col w-full">
      {% block content %}

      {% endblock %}
    </main>

    {% include 'components/footer.html' %}
  </body>
</html>

landing/templates/landing/government.html
{% extends 'landing.html' %}

{% block head %}
  <style>
    #content {
      p {
        color: #888;
        font-size: 1.4em;
        text-align: justify;
    
        @media screen and (max-width: 768px) {
          font-size: 1em;
        }
      }
    }
  </style>
{% endblock %}

{% block content %}
  <section class="w-full py-20 flex items-center justify-center from-green-300 to-green-700 bg-gradient-to-br">
    <h2 class="text-white font-bold capitalize text-xl md:text-6xl drop-shadow-md">{{ member.name }}</h2>
  </section>

  <section class="w-full flex flex-col gap-4 items-start justify-start px-[10%] py-10">
    {% if member.image %}
      <img src="{{ member.image.url }}" alt="" class="w-full max-h-[60vh] object-contain" />
    {% endif %}
  </section>

  <section id="content" class="w-full flex flex-col items-start justify-start gap-4 px-[10%] py-10 text-justify md:text-left">{{ member.formatted_content|safe }}</section>
{% endblock %}

landing/templates/landing/mda.html
{% extends 'landing.html' %}

{% block content %}{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>